### ISSUE TITLE
Einbindung der Wetter API

### ISSUE THREAD

**Issue by mai-space** [Inf166/TelegramWeatherAlerts#3]
[Link zur Wetter-API](http://www.wetter-api.de/)

**Comment by IceQ1337** [comment]
Grundgerüst ermöglicht Nutzung von: https://openweathermap.org/api

**Comment by mai-space** [comment]
### New Idea
`/weather <city-name>` gives you the tempreture and weather status everytime it changes

**Comment by mai-space** [comment]
`/weather` liefert die aktuelle Temperatur des angegebenen Ortes

**Comment by IceQ1337** [comment]
Einbindung ist erfolgt. Commands verworfen.
