### ISSUE TITLE
Einbindung von Telegram

### ISSUE THREAD

**Issue by mai-space** [Inf166/TelegramWeatherAlerts#6]
**Is your feature request related to a problem? Please describe.**
Bisher überlegen wir ja nur die Konsole als Eingabe zu benutzen, aber mit Telegram wäre das Ganze der Realität ein Stückchen näher. @IceQ1337 Wollte sich damit befassen.

**Describe the solution you'd like**
Er schlug vor einen einfachen Login mit Telegram zu basteln und dann dort die Infos der API von Wetter und Route zu erhalten

**Describe alternatives you've considered**
Die Alternative wäre halt weiterhin die Konsole zu verwenden...

**Comment by IceQ1337** [comment]
Grundgerüst ermöglicht Nutzung eines Telegram Bots.
